server:
  port: 8082

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:h2:mem:itemdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    com.ics.itemdetails: DEBUG
